USE ROLE ACCOUNTADMIN;

USE DATABASE SUPERANNUATION;
USE SCHEMA GOLD;

SELECT COUNT(DISTINCT member_id)
FROM SUPERANNUATION.GOLD.FACT_MEMBER_CONTRIBUTION_PERFORMANCE;

SELECT COUNT(DISTINCT member_id)
FROM SUPERANNUATION.GOLD.DIM_MEMBER;

SELECT COUNT(DISTINCT relationship_id)
FROM SUPERANNUATION.GOLD.DIM_EMPLOYER;

SELECT COUNT(DISTINCT employment_id)
FROM SUPERANNUATION.GOLD.DIM_EMPLOYMENT;

SELECT *
FROM SUPERANNUATION.GOLD.FACT_MEMBER_CONTRIBUTION_PERFORMANCE
WHERE contribution_efficiency_ratio IS NULL;

SELECT *
FROM SUPERANNUATION.GOLD.DIM_EMPLOYER
WHERE industry IS NULL;

SELECT MAX(combined_contribution_rate)
FROM SUPERANNUATION.GOLD.FACT_MEMBER_CONTRIBUTION_PERFORMANCE;